#!/bin/sh


#MIT License
#
#Copyright (c) 2016 Steven P. Crain, SUNY Plattsburgh
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

if [ -z "$1" ]
  then
    PROG=demo.py
  else
    PROG="$1"
fi

if [ -z "$2" ]
  then
    SRC=easy
  else
    SRC="$2"
fi

LOC="/tmp/$LOGNAME/crushertest-$SRC"
HERE=`pwd`

rm -rf "$LOC"

mkdir -p "$LOC"
cd "$LOC"

"$HERE/$PROG" "/local/files/scrai002/csc456/input/$SRC.txt"
sed -e 's/^CAST	.*/CAST/' "$SRC-votelog.txt" > votelog.$$
sed -ne 's/^CAST	/INQ	/p' -e '/^CONF/p'  "$SRC-votelog.txt" > "$SRC.txt"
cp "$SRC-votelog.txt" votelog.txt
sort "$SRC-results.txt" > results.$$
"$HERE/$PROG" "$SRC.txt"

cat <<EOF
Votelog Errors: `diff votelog.$$ "/local/files/scrai002/csc456/correct/$SRC-votelog.txt" | wc -l`
Results Errors: `diff results.$$ "/local/files/scrai002/csc456/correct/$SRC-results.txt" | wc -l`
Inquiry Errors: `diff "votelog.txt" "$SRC-votelog.txt" | wc -l`
EOF
