#!/bin/sh


# This script was used to download the results from the Alamedda COunty, CA
# presidential election in Nov 2016.
#
#MIT License
#
#Copyright (c) 2016 Steven P. Crain, SUNY Plattsburgh
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.

wget 'http://www.acgov.org/rov/current_election/230/menuNF.htm'

sed -ne 's/.*<li><a href="\([^"]*\)">\([^<]*\).*/\2	\1/p' menuNF.htm > offices

rm -f offices.tsv

#cat <<EOC
cat offices | while IFS="	" read office url
  do
    if [ -s "$office.htm" ]
      then :
      else
        wget "http://www.acgov.org/$url" -O "$office.htm"
    fi

    sed -ne 's@.*<[^>]*class="\([^"]*\)"[^>]*>\(.*\)@\1	\2@p' "$office.htm" | sed -e 's@<[^>]*>@@g' -e 's/^voteFor	.*\([1-4]\).*/voteFor	\1/' -e 's/^totprecincts	[^0-9]*\([0-9][0-9]*\).*/totprecincts	\1/' > "$office.dat"

    awk 'BEGIN { voteFor=1 }
         /^raceName	/ { raceName=$2 }
         /^voteFor	/ { voteFor=$2}
         /^totprecincts	/ { totprecincts=$2}
         /^can	/ { can="Yes"
                    voteFor=1
                    if(currentVotes>totVotes)
                      totVotes=currentVotes
                    currentVotes=0
                  }
         /^can name	/ { canName=$2}
         /^can votes	/ { canVotes=$2}
         /^can percent	/ { if(can)
                            { print canName, can, canVotes, $2
                              can="No"
                              currentVotes+=canVotes
                            } else
                            { print raceName, canName, canVotes, $2
                              totVotes+=canVotes
                            }
                          }
         END { if(currentVotes>totVotes)
                 totVotes=currentVotes
               print "STATS", raceName, totprecincts, voteFor, totVotes, totVotes/voteFor
             }' FS='	' OFS='	' "$office.dat" >> offices.tsv

done
cat <<EOC
EOC

grep '^STATS	' offices.tsv | sort -t '	' -k 3,3 -k 6,6 -n > offices.stats
